version: '3.7'

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static:/static:rw
    restart: on-failure
    labels:
      - "traefik.backend=back"
      - "traefik.enable=true"
      - "traefik.http.routers.back.rule=Host(`back.localhost`)"
      - "traefik.http.routers.back.entrypoints=web"
  traefik:
    image: traefik:latest
    container_name: "traefik"
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
      - "8080:8080"

volumes:
  static:
